Repository simde-utc/payutc-mobile, pull requests merged in 2019-08, with the labels that each got.

#113 Add iOS splash screen, app icon and remove tvOS folders
  ios/PayUTC-tvOS/Info.plist
  ios/PayUTC-tvOSTests/Info.plist
  ios/PayUTC.xcodeproj/project.pbxproj
  ios/PayUTC.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/PayUTC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/PayUTC/Base.lproj/LaunchScreen.xib
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-1024.png
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-20@2x.png
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-20@3x.png
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-29@2x.png
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-29@3x.png
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-40@2x.png
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-40@3x.png
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-60@2x.png
  ios/PayUTC/Images.xcassets/AppIcon.appiconset/payutc-logo-60@3x.png
  ios/PayUTC/Images.xcassets/Contents.json
  ios/PayUTC/Images.xcassets/LaunchImage.launchimage/Contents.json
  ios/PayUTC/Images.xcassets/icon.imageset/Contents.json
  ios/PayUTC/Images.xcassets/icon.imageset/icon.png
  ios/PayUTC/Info.plist
Labels: ios

#114 Add translation for back button on iOS
  src/locales/en.json
  src/locales/fr.json
  src/screens/Auth/AuthScreen.js
  src/screens/History/HistoryScreen.js
  src/screens/Home/HomeScreen.js
  src/screens/Home/PaymentScreen.js
  src/screens/Home/RefillScreen.js
  src/screens/Home/TransferScreen.js
  src/screens/Settings/AboutScreen.js
  src/screens/Settings/ContributorsScreen.js
  src/screens/Settings/DependenciesScreen.js
  src/screens/Settings/LicenseScreen.js
  src/screens/Settings/SettingsScreen.js
  src/screens/Stats/StatsScreen.js
Labels: ios

#115 Remove shadow under Android and improve global render
  src/components/BlockTemplate.js
  src/components/TabsBlockTemplate.js
  src/components/TitleParams.js
Labels: android, ios

#128 Add border around suggestions on Android
  src/components/Home/Balance.js
  src/components/Refill/AmountForm.js
  src/components/Transfer/MessageForm.js
Labels: android

#129 Fix submit issues
  src/components/Refill/Submit.js
  src/components/Transfer/MessageForm.js
  src/components/Transfer/Submit.js
Labels: UI/UX

#126 Fix TextInput issues on Android
  src/components/Home/AmountInput.js
  src/components/Refill/AmountForm.js
  src/components/Transfer/AmountForm.js
  src/components/Transfer/MessageForm.js
  src/components/Transfer/RecipientForm.js
  src/screens/Auth/AuthScreen.js
  src/screens/History/HistoryScreen.js
Labels: android

#152 Improve inputs by adding auto selections
  src/components/AmountForm.js
  src/components/Home/AmountInput.js
  src/components/Refill/Submit.js
  src/components/Transfer/AmountForm.js
  src/components/Transfer/MessageForm.js
  src/components/Transfer/RecipientForm.js
  src/components/Transfer/Submit.js
  src/screens/Auth/AuthScreen.js
  src/screens/Home/RefillScreen.js
  src/screens/Home/TransferScreen.js
Labels: UI/UX

#153 Fix the version checker
  src/screens/AppLoader.js
Labels: bug

#163 Search also with the fundation
  src/screens/History/HistoryScreen.js
Labels: enhancement

#181 Add profile screen
  config.example.js
  src/components/Paragraphe.js
  src/components/TitleParams.js
  src/locales/en.json
  src/locales/fr.json
  src/navigations/Settings/SettingsNavigator.js
  src/screens/History/HistoryScreen.js
  src/screens/Home/HomeScreen.js
  src/screens/Settings/ProfileScreen.js
  src/screens/Settings/SettingsScreen.js
  src/screens/Stats/StatsScreen.js
  src/services/PayUTC.js
  src/utils/i18n.js
Labels: data, feature

#197 Fix definitly depreciated versions
  src/screens/AppLoader.js
Labels: bug
